# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcmd.proto\x12\x05psMCU\"\x85\x01\n\x03\x43md\x12 \n\x04type\x18\x01 \x02(\x0e\x32\x12.psMCU.Cmd.CmdType\x12\x0e\n\x06\x61\x63k_py\x18\x02 \x02(\x08\x12\x0e\n\x06\x61\x63k_rs\x18\x03 \x02(\x08\x12\r\n\x05\x61\x63k_c\x18\x04 \x02(\x08\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\"\x1c\n\x07\x43mdType\x12\x08\n\x04PING\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cmd_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CMD._serialized_start=21
  _CMD._serialized_end=154
  _CMD_CMDTYPE._serialized_start=126
  _CMD_CMDTYPE._serialized_end=154
# @@protoc_insertion_point(module_scope)
